### ISSUE TITLE
Controller-Updating function-Sara

### ISSUE THREAD

**Issue by Sara-webaplication** [Cascadia-Connections/photo-points#2]
Adding function update submission to AdminController 

DoD: Done when user can update or add all information that they need

**Comment by Bansenauer-Cascadia** [comment]
The DoD is not specific enough. What information is the user adding or updating? What is the information about? What is the AdminController for?

**Comment by Sara-webaplication** [comment]
User Story that is Addresses: Project team approves the data architecture
