### ISSUE TITLE
foreach loop to display pending capture images for review and approval

### ISSUE THREAD

**Issue by sruble** [Cascadia-Connections/photo-points#41]
DOD: when the view displays pending captures.

**Comment by Bansenauer-Cascadia** [comment]
Your issue name is a bit too specific to how you will do the work. Instead, the name focused on the end goal. Something like, "Display pending capture images for review and approval"

Also include a comment that links this to a User Story from your MVP

**Comment by sruble** [comment]
MVP User Story: The administrator is logged into their account on the Welcome page and would like to view the pending images. The administrator clicks on the Pending page option and sees images submitted by local users.

**Comment by sruble** [comment]
should this one be labeled duplicate? The issue number #53,  ienumerables sim#41,  is supposed to be this issue. This is one of this instances where issue cards are still a little unclear
