### ISSUE TITLE
UI controllers to approve and reject pending submissions

### ISSUE THREAD

**Issue by sruble** [Cascadia-Connections/photo-points#64]
DOD: when there are user interface options, connected to each image, to  approve or reject submissions

**Comment by floydfix** [comment]
Backlog: Approve and Deny buttons below each photo that is pending approval

DOD: Pending capture card view has options to approve and deny the pending capture that duplicates the look and urls from the matching action buttons at /Admin/Details?id=1
Also, make the Remove action link match the styling from the details page and make the user confirm before deleting
